name: Test

on:
  push:
    branches:
      - testing

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.1

      - name: Install dependencies
        run: npm install

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.1

      - name: Test
        run: npm run test