name: Test

on:
  push:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.1'
        run: npm install

      - name: Test
        run: npm run test